ALTER TABLE products ADD COLUMN sizes VARCHAR(255) DEFAULT NULL;
ALTER TABLE products ADD COLUMN colors VARCHAR(255) DEFAULT NULL;

ALTER TABLE order_details ADD COLUMN size VARCHAR(50) DEFAULT NULL;
ALTER TABLE order_details ADD COLUMN color VARCHAR(50) DEFAULT NULL;
